[env]
TERM = "xterm-256color"

[font.normal]
family = "SauceCodePro NF"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[general]
import = [
  "~/.alacritty.theme.toml",
  "~/.alacritty.local.toml",
]
