#!/bin/bash

chmod +x $HOME/bin/*

# Symlink fish plugins
# TODO: Improve
for type in completions conf.d functions themes; do
  mkdir -p "$HOME/.config/fish/$type"
  for file in $HOME/.config/fish/plugins/*/$type/*; do
    ln -sf "$file" "$HOME/.config/fish/$type/$(basename "$file")"
  done
done
