gaps:
  inner_gap: 20
  outer_gap: 20

bar:
  height: "30px"
  position: "top"
  opacity: 1.0
  background: "#eee8d5"
  foreground: "#002b36"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "4px 6px"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#fdf6e3"
      displayed_workspace_background: "#000000"
      default_workspace_background: "transparent"
  components_right:
    - type: "tiling direction"
      background: "#fdf6e3"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#fdf6e3"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      time_formatting: "hh:mm tt  ddd MMM d"
      margin: "0 0 0 10px"

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running the WM as admin.
  - command: "ignore"
    match_process_name: "Taskmgr"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

binding_modes:
  - name: "resize"
    keybindings:
      - command: "resize width -5%"
        binding: "Left"
      - command: "resize width +5%"
        binding: "Right"
      - command: "resize height +5%"
        binding: "Up"
      - command: "resize height -5%"
        binding: "Down"
      - command: "binding mode none"
        binding: "Escape"

keybindings:
  - command: "focus left"
    binding: "Alt+Left"
  - command: "focus right"
    binding: "Alt+Right"
  - command: "focus up"
    binding: "Alt+Up"
  - command: "focus down"
    binding: "Alt+Down"

  - command: "move left"
    binding: "Alt+Shift+Left"
  - command: "move right"
    binding: "Alt+Shift+Right"
  - command: "move up"
    binding: "Alt+Shift+Up"
  - command: "move down"
    binding: "Alt+Shift+Down"

  - command: "binding mode resize"
    binding: "Alt+Shift+Z"

  - command: "tiling direction horizontal"
    binding: "Alt+Shift+H"
  - command: "tiling direction vertical"
    binding: "Alt+Shift+V"

  - command: "toggle focus mode"
    binding: "Alt+Shift+Space"

  - command: "toggle floating"
    binding: "Alt+Space"

  - command: "toggle maximized"
    binding: "Alt+Shift+F"

  - command: "close"
    binding: "Alt+Shift+W"

  - command: "exec wt"
    binding: "Alt+Enter"

  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  - command: "move to workspace 1"
    binding: "Alt+Shift+1"
  - command: "move to workspace 2"
    binding: "Alt+Shift+2"
  - command: "move to workspace 3"
    binding: "Alt+Shift+3"
  - command: "move to workspace 4"
    binding: "Alt+Shift+4"
  - command: "move to workspace 5"
    binding: "Alt+Shift+5"
  - command: "move to workspace 6"
    binding: "Alt+Shift+6"
  - command: "move to workspace 7"
    binding: "Alt+Shift+7"
  - command: "move to workspace 8"
    binding: "Alt+Shift+8"
  - command: "move to workspace 9"
    binding: "Alt+Shift+9"

